//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public long Id { get; set; }
        public string DataName { get; set; }
        public Nullable<int> Address { get; set; }
        public string Unit { get; set; }
        public Nullable<int> AlarmValue { get; set; }
        public Nullable<int> StopValue { get; set; }
    }
}
