//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reprint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReprintEntities : DbContext
    {
        public ReprintEntities()
            : base("name=ReprintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Alarm> Alarm { get; set; }
        public virtual DbSet<DefineChannal> DefineChannal { get; set; }
        public virtual DbSet<SystemStanderd> SystemStanderd { get; set; }
        public virtual DbSet<TestData> TestData { get; set; }
        public virtual DbSet<TestDefineVarible> TestDefineVarible { get; set; }
        public virtual DbSet<TestInfo> TestInfo { get; set; }
        public virtual DbSet<WorkStation> WorkStation { get; set; }
    }
}
