//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStation
    {
        public long Id { get; set; }
        public string TestType { get; set; }
        public string TestCode { get; set; }
        public Nullable<int> WorkStationId { get; set; }
        public Nullable<int> SetRunSpeed { get; set; }
        public Nullable<int> SetLongTime { get; set; }
        public Nullable<int> SetActiveTime { get; set; }
        public Nullable<double> HighTemp { get; set; }
        public Nullable<double> LowTemp { get; set; }
        public Nullable<int> AcrossSpeed { get; set; }
        public Nullable<double> HeatTemp { get; set; }
        public Nullable<double> CoolTemp { get; set; }
    }
}
